### ISSUE TITLE
Required packages

### ISSUE THREAD

**Issue by marcus151** [justinesmithies/qtile-wayland-dotfiles#1]
Hi justinesmithies, 
can you perhaps provide a list of needed packages/dependencies? I tried to switch from xorg/bspwm to wayland/qtile based on your config files. Qtile also starts, but apparently some packages are missing. I have installed all the programs you listed. The main installation is an arch with archinstall and profile "minimal". 

Maybe a complete installation guide would be great. 
Greetings from Germany ;-)

**Comment by justinesmithies** [comment]
Hello from Scotland ;-)
You say Qtile starts but some packages are missing can you expand on what is not working with logs or screenshots ?
Could you post your Qtile log file with.
`cat .local/share/qtile/qtile.log`

**Comment by marcus151** [comment]
Hi, got it done now. No idea where the error was. Tried the whole thing again under xorg and it works. So again, wipe off and install wayland without xorg and now it runs perfectly!
And thanks to your bashrc I figured out how to change the keyboard layout :)
